version: "3.7"

services:
  web:
    image: ewave112/metawars:prod
    build:
      context: .
      target: prod
    container_name: metawars
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_URI=${DB_URI}

    networks:
      - metawars-network

networks:
  metawars-network:
    name: metawars-network
